export default function TermAndCondition() {
    return (
        <div className='xl:px-72 md:px-26 px-10 py-8 bg-[#1a0033] text-white'>
            <h1 className='text-center text-[22px] font-bold'>Terms of Service</h1>
            <p className='font-semibold mt-2 mb-2'>fanfavout.themccandlessgroup.com</p>
            <p>fanfavout.themccandlessgroup.com provides the ability for Models and Users to connect online and for users to subscribe to content published by Models (the “Service”) offered from time to time at Demo.TheMcCandlessGroup.com and/or via an App (collectively the “Sites” or the “Site”). The Service and the Site may be collectively referred to herein as the “Platform.” This Terms of Service is directed at Users who visit a Model’s Site. The Service is owned and operated by McCandless Group, LLC (“Company” or “we” or “us”).</p>
            <p className="mt-2 mb-2">Your use of the Service is subject to the terms and conditions set forth in this Terms of Service (the “Terms of Service” “Terms” or “TOS”).</p>
            <p className="mt-2 mb-2"><strong>PLEASE READ THE TERMS OF SERVICE CAREFULLY. BY ACCESSING OR USING ANY PART OF THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY ALL THE TERMS OF THIS TOS. IF YOU DO NOT AGREE TO THESE TERMS OF SERVICE, EXIT THIS PAGE AND DO NOT ACCESS OR USE THE SERVICE. USE OF THE SERVICE IS EXPRESSLY CONDITIONED UPON YOUR ACCEPTANCE OF THE TERMS OF SERVICE.</strong></p>
            <p><strong>Updates to Terms of Service; Integration.</strong> We may, in our sole discretion, modify the Terms of Service by posting a notice on the Terms of Service page. The “Last Updated” date at the top the Terms of Service indicates when the latest modifications were made to the TOS. By continuing to access and use the Service you agree to any such modifications. Therefore, you are responsible for reviewing and should become familiar with any such modifications. You are encouraged to review this Terms of Service periodically and to check the “Last Updated” date at the top of the Terms of Service for the most recent version. In addition, when using services or features on the Site, you will be subject to any posted guidelines or policies applicable to such services or features that may be posted from time to time, including but not limited to our Privacy Policy, as noted below. All such guidelines or policies are hereby incorporated by reference into this Terms of Service.</p>
            <p className='font-bold mt-2 mb-2'><strong>Service Availability.</strong></p>
            <p>The Service may be modified, updated, interrupted, suspended or discontinued at any time, in the sole discretion of the Company, without notice or liability. The Service may be unavailable at certain periods, including but not limited to systems failures, anticipated or unanticipated maintenance work, upgrades or force majeure events.</p>
            <p>The Company reserves the right, at any time, in its sole discretion to modify, temporarily or permanently block access to, suspend, or discontinue the Service, in whole or in part, with or without notice and effective immediately to any User.</p>
            <p>The Company will have no liability whatsoever for any losses, liabilities or damages you may incur as the result of any modification, suspension, or discontinuation of the Service or any part thereof.</p>
            <p className='mt-2 mb-2'><strong>Privacy Policy.</strong> Use of the Service is subject to the terms of our <a href='/privacy-policy' target='_self'>Privacy Policy</a> which is here by incorporated into and made part of this Terms of Service. Please carefully review our Privacy Policy. By using or accessing the Service, you agree to be bound by the terms of our Privacy Policy.</p>
            <p className='mt-2 mb-2'><strong>Age.</strong> The Service is meant for those at least eighteen (18) years of age. Use of the Service by anyone under this age is a violation of the Terms of Service.</p>
            <p className='font-bold mt-2 mb-2'><strong>Intellectual Property.</strong></p>
            <p>You acknowledge that all the intellectual property rights in the Service, including, but not limited to, copyrights, patents, trademarks, and trade secrets, the website design, application design, graphics, text, sounds, pictures, service marks, trade names, domain names, slogans, logos, and other indicia of origin that appear on or in connection with any aspect of the Service and other files and the selection and arrangement thereof (collectively the “Materials”) are either the property of the Company, its affiliates or licensors and other files and the selection and arrangement thereof (collectively the “Materials”) and are subject to and protected by United States and international copyright and other intellectual property laws and rights. All rights to Materials not expressly granted in these Terms of Service are reserved to their respective copyright owners.</p>
            <p>Subject to this TOS, the Company grants you a limited non-transferable, non-exclusive, revocable, non-sublicensable licence to use and access the Service solely for your own personal or internal business purposes. You will not obtain any ownership interest therein through this Terms of Service or otherwise.</p>
            <p>Except as expressly authorized by the Terms of Service, you may not copy, reproduce, distribute, republish, download, perform, display, post, transmit, scrape, copy, exploit, create derivative works or otherwise use any of the Materials in any form or by any means, without the prior written authorization of Company or the respective copyright owner. In the absence of a written agreement, you may not modify or adapt the Materials in any way or otherwise use them for any public or commercial resale purposes. The Company retains the right to rescind and terminate the limited license granted hereunder at any time for any or no reason. The Company reserves the right to enforce its intellectual property rights fully under United States and international law.</p>
            <p>Some of the company and product names, logos, brands, and other trademarks featured or referred to within the Service may not be owned by us and are the property of their respective trademark holders. These trademark holders are not affiliated with, nor do they sponsor or endorse the Service.</p>
            <p className='font-bold mt-2 mb-2'><strong>Use of the Service, General</strong></p>
            <p>In order to use the Service you may be required to create an account to use the Service and/or take advantage of certain features, you agree to:</p>
            <p>a. provide true, accurate, current and complete information about yourself as prompted by the Service;</p>
            <p>b. as permitted, maintain and promptly update such information. If you provide any information that is false, inaccurate or outdated, or Company has reasonable grounds to suspect that such information is false, inaccurate or outdated, Company has the right to suspend or terminate your account and prohibit all current or future use of the Service by you; and</p>
            <p>c. that your account is for your personal and/or business use. You may not resell the Service.</p>
            <p>d. by creating an account, you agree to receive certain communications in connection with the Service.</p>
            <p>You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all activities that occur under your account. Your account is meant to be private and you shall not share accounts for any reason. You agree to immediately notify us of any unauthorized use of your password or account or any other breach of security. You agree to be responsible for all charges resulting from the use of your account via the Service, including charges resulting from unauthorized use of your account.</p>
            <p>You may not impersonate someone else, create or use an account for anyone other than yourself, provide an email address other than your own, or create multiple accounts.</p>
            <p>You agree to use the Service only for lawful purposes and that you are responsible for your use of and communications and content you may post via the Service. You agree not to post or transmit any unlawful, infringing, threatening, harassing, defamatory, vulgar, obscene, profane, indecent, offensive, hateful or otherwise objectionable material of any kind, including any material that encourages criminal conduct or conduct that would give rise to civil liability, infringes upon others’ intellectual property rights, impersonates any individual or entity, or otherwise violates any applicable law. You agree not to solicit personal information from minors. You agree not to use the Service in any manner that interferes with its normal operation or with any other user’s use of the Service.</p>
            <p>You may not do any of the following while accessing or using the Service:</p>
            <p>a. access, tamper with, or use non-public areas of the Service, our computer systems, or the technical delivery systems of our providers;</p>
            <p>b. probe, scan, or test the vulnerability of any system or network or breach or circumvent any security or authentication measures;</p>
            <p>c. access or search or attempt to access or search the Service by any means other than through our currently available, published interfaces that are provided by us, unless you have been specifically allowed to do so in a separate agreement with us;</p>
            <p>d. forge any TCP/IP packet header or any part of the header information in any email or posting, or in any way use the Service to send altered, deceptive or false source-identifying information; or</p>
            <p>e. disrupt or interfere with the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, mail-bombing the Service, or otherwise creating an undue burden on the Service.</p>
            <p>You may not use manual or automated software, devices, or other processes to “crawl,” “scrape,” or “spider” any page of the Service. You will not decompile, reverse engineer, or otherwise attempt to obtain the source code of any part of the Service.</p>
            <p>You further agree that you will not access the Service by any means except through the interface provided by Company for access to the Service. Creating or maintaining any link from another application to any page at the Service without the prior authorization of Company is prohibited. Running or displaying the Service, or any information or material displayed via the Service in frames or through similar means on another website or application without the prior authorization of Company is prohibited. Any permitted links to the Service must comply with all applicable laws, rule and regulations.</p>
            <p>Company makes no representation that Materials contained, described or offered via the Service are accurate, appropriate or available for use in any particular jurisdiction or that these Terms of Service comply with the laws of any specific country. Visitors who use the Service do so on their own initiative and are responsible for compliance with all applicable law. You agree that you will not access the Service from any territory where its contents are illegal, and that you, and not the Company Parties, are responsible for compliance with applicable law.</p>
            <p>Your use of the Service is at your own risk, including the risk that you might be exposed to content that is offensive, indecent, inaccurate, objectionable, or otherwise inappropriate.</p>
            <p>Furthermore, you herein agree not to make use of the Services for:</p>
            <p>a. uploading, posting, emailing, transmitting, or otherwise making available any content that shall be deemed unlawful, harmful, threatening, abusive, harassing, tortious, vulgar, obscene, libelous, or invasive of another's privacy or which is hateful, and/or racially, ethnically, or otherwise objectionable;</p>
            <p>b. causing harm to any minor in any manner whatsoever;</p>
            <p>c. impersonating any individual or entity, including, but not limited to, any Company, group or forum leaders, or hosts or falsely stating or otherwise misrepresenting any affiliation with an individual or entity;</p>
            <p>d. forging captions, headings or titles or otherwise offering any content that you personally have no right to pursuant to any law nor having any contractual or fiduciary relationship with;</p>
            <p>e. uploading, posting, emailing, transmitting or otherwise offering any such content that may infringe upon any patent, copyright, trademark, or any other proprietary or intellectual rights of any other party;</p>
            <p>f. uploading, posting, emailing, transmitting or otherwise offering any content that you do not personally have any right to offer pursuant to any law or in accordance with any contractual or fiduciary relationship;</p>
            <p>g. uploading, posting, emailing, transmitting, or otherwise offering any unsolicited or unauthorized advertising, promotional flyers, 'junk mail,' 'spam,' or any other form of solicitation, except in any such areas that may have been designated for such purpose;</p>
            <p>h. uploading, posting, emailing, transmitting, or otherwise offering any source that may contain a software virus or other computer code, any files and/or programs which have been designed to interfere, destroy and/or limit the operation of any computer software, hardware, or telecommunication equipment;</p>
            <p>i. disrupting the normal flow of communication, or otherwise acting in any manner that would negatively affect other users' ability to participate in any real-time interactions;</p>
            <p>j. interfering with or disrupting any of the Services, servers and/or networks that may be connected or related to our website, including, but not limited to, the use of any software and/or routine to bypass the robot exclusion headers;</p>
            <p>k. intentionally or unintentionally violating any local, state, federal, national or international law, including, but not limited to, rules, guidelines, and/or regulations decreed by the Securities and Exchange Commission, in addition to any securities rules, regulations or laws of any nation or other securities exchange, and any regulations having the force of law;</p>
            <p>l. providing informational support or resources, concealing and/or disguising the character, location, and or source to any organization delegated by the United States government as a 'foreign terrorist organization' in accordance to Section 219 of the Nationality Act;</p>
            <p>m. stalking or with the intent to otherwise harass another individual; and/or,</p>
            <p>n. collecting or storing of any personal data relating to any other user in connection with the prohibited conduct and/or activities which have been set forth in the aforementioned paragraphs.</p>
            <p className='font-bold mt-2 mb-2'>Third Party Websites</p>
            <p>In the event we include links via the Service to Third-Party websites (including advertisements), which may include products, goods, services or information offered therein, these are provided only as a convenience. If you clickthrough using these links to other websites, you may leave our Site. We do not control nor endorse any such Third-Party websites. You agree that the Company Parties, as defined below, will not be responsible or liable for any content, products, goods, services or information provided or available via any Third-Party website or for your use or inability to use a Third-Party website.</p>
            <p>You will use such links at your own risk. You are advised that other websites on the Internet, including Third-Party websites linked from our Site, might contain material or information:</p>
            <p>a. that some people may find offensive or inappropriate;</p>
            <p>b. that is inaccurate, untrue, misleading or deceptive; or,</p>
            <p>c. that is defamatory, libelous, infringing of others’ rights or otherwise unlawful.</p>
            <p>We expressly disclaim any responsibility for the content, legality, decency or accuracy of any information, and for any content, products, goods, services or information, that appear on any Third-Party website or in advertisements or content that Third Parties may have listed or offered on our Site.</p>
            <p>Your interactions with Third Parties found on or through the Service, including payment and delivery of goods or services, if any, conditions, warranties or representations associated with such matters are solely between you and the Third Parties, except as may be otherwise stated herein. You acknowledge and agree that Company is not a party to any transactions you may enter into, except as may otherwise be stated herein, using the Service and we shall not under any circumstances be liable for any damages of any kind arising out of, or in connection with, or relating to, the content, products, goods, services or information of a Thirty-Party.</p>
            <p className='font-bold mt-2 mb-2'>User Content</p>
            <p>“User Content” means any and all information and content that a user submits to, or uses with, the Services, including but not limited to, content in the user’s profile or postings. You may choose to enter this information manually or, where available, synchronize with a third-party website. The Company does not verify the accuracy or completeness of User Content and these may therefore be subject to errors.</p>
            <p>You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that personally identifies you or any third party. You hereby represent and warrant that your User Content does not violate any of the Terms of Service.</p>
            <p>You may not represent or imply to others that your User Content is in any way provided, sponsored or endorsed by Company. Because you alone are responsible for your User Content, you may expose yourself to liability if, for example, your User Content violates this Terms of Service in any way.</p>
            <p>Company does not and is not obligated to backup any User Content, and your User Content may be deleted at any time without prior notice. You are solely responsible for creating and maintaining your own backup copies of your User Content.</p>
            <p>We may, at our discretion, pre-screen User Content submission and may choose to remove User Content at any time we see fit. You agree that the Company is not responsible for any financial loss, liability or damage of any kind that you may incur as a result of our removing or refusing to publish User Content.</p>
            <p>We reserve the right, but have no obligation, to review any User Content, and to investigate and/or take appropriate action against you in our sole discretion if you violate these Terms of Service or otherwise create liability for us or any other person. Such action may include removing or modifying your User Content, terminating your Account, and/or reporting you to law enforcement authorities.</p>
            <p>You understand that the Company is not liable for any third-party communications that you may receive from third parties or affiliates of the Company, in connection with your account. You are solely responsible for evaluating and verifying the identity and trustworthiness of any correspondence you receive. The Company makes no representations or warranties with regards to the accuracy, trustworthiness or identity of third-party communications.</p>
            <p>Suggestions and Improvements. By sending us any ideas, suggestions, documents or proposals (“Feedback”), you agree that (i) your Feedback does not contain the confidential or proprietary information of third parties, (ii) we are under no obligation of confidentiality, express or implied, with respect to the Feedback, (iii) we may have something similar to the Feedback already under consideration or in development, and (iv) you grant us an irrevocable, non-exclusive, royalty-free, perpetual, worldwide license to use, modify, prepare derivative works, publish, distribute and sublicense the Feedback, and (v) you irrevocably waive, and cause to be waived, against the Company Parties and its users any claims and assertions of any moral rights contained in such Feedback.</p>
            <p className='mt-2 mb-2'><strong>Representations.</strong> You expressly acknowledge, represent, warrant, and agree that you understand:</p>
            <p>The information contained herein is for informational purposes only and is not intended as nor should be construed as advice or recommendations and are not guaranteed to produce results.</p>
            <p>Company does not warrant or guarantee the suitability or availability of any material or content, including without limitation any, data, products or services, found through the Service.</p>
            <p>Company does not screen the authenticity or quality of any material or content or any provider of material or content, including, data, products or services found through the Service.</p>
            <p>Company makes no representations or promises regarding any material or content, and that some of the material or content provided via the Service may be owned or licensed by Third Parties.</p>
            <p>Company is not a party to any transaction between you and any provider of products or services via the Service except as may be specifically stated herein. Any dispute shall be resolved between yourself and the provider of such products or services or your customer.</p>
            <p>Any information, including any data, Company Materials, or content on the Site, including on any Company Facebook, Instagram or Twitter or other social media pages, are for informational purposes only.</p>
            <p>You assume all risk when using the Service, including all the risks associated with any online or offline interactions with other users, providers of products and services, and from additional fees or charges from your mobile carrier.</p>
            <p>You are of legal age to form a binding contract and are at least the age as noted earlier herein, or of the age of majority where you reside, or you have the authority of such legal entity to form a binding contract; all registration information you submit is accurate and truthful; you will maintain the accuracy of such information; and you are legally permitted to use and access the Service and take full responsibility for the selection and use of and access to the Service.</p>
            <p className='font-bold mt-2 mb-2'>Indemnification</p>
            <p>You agree to indemnify, defend and hold harmless the Company, its parents, subsidiaries and other affiliated companies, and their respective officers, directors, employees, agents and other representatives (collectively, the “Company Parties”) against all claims, demands, causes of action, losses, expenses, damages and costs (including any reasonable attorneys’ fees), resulting or arising from or relating to your use of the Service, any activity related to your account by you or any other person permitted by you, any Content that you submit to, post on or transmit through the Service, your breach of this Terms of Service, your infringement or violation of any rights of another, or termination of your access to the Service. We reserve the right to assume, at our sole expense, the exclusive defense and control of any such claim or action and all negotiations for settlement or compromise, and you agree to fully cooperate with us in the defense of any such claim, action, settlement or compromise negotiations, as requested by us.</p>
            <p>You hereby release and forever discharge the Company Parties from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, or that relates directly or indirectly to, the Service, including any interactions with, or act or omission of, other Service users or any Third-Party sites, including but not limited to: (i) your use of the Service, (ii) any activity related to your accounts by you or any other person, (iii) your violation of this Terms; (iv) your infringement or violation of any rights of another, (v) your violation of applicable laws or regulations, or (vi) your User Content.</p>
            <p>Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us, and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of Company. Company will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
            <p className='mt-2 mb-2'><strong>Warranties, Disclaimers and Limitations of Liability.</strong> You expressly understand and agree that:</p>
            <p>Your use of the Service is at your sole risk. The Service and the associated materials and content are provided on an “as is” and “as available” basis. The Company, its parents, subsidiaries and other affiliated companies, and their respective officers, directors, employees, agents and other representatives (collectively, the “Company Parties”), expressly disclaim all warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a purpose and non-infringement. Without limiting the generality of the foregoing, the Company Parties make no warranty that: (i) the Service will meet your requirements; (ii) the Service will be uninterrupted, timely, secure, or error-free; (iii) information that may be obtained via the Service will be accurate or reliable; (iv) the quality of any and all products, services, information or other materials, including all merchandise, products, goods or services, obtained or purchased by you directly or indirectly through the company Service will meet your expectations or needs; and (v) any errors in the Service will be corrected.</p>
            <p>The Company Parties shall not under any circumstances be liable for any damages of any kind arising out of, in connection with or relating to the use of or inability to use the Service, including any liability: (i) as a publisher of information; (ii) for any incorrect or inaccurate information or any ‘bug’ of the Service; (iii) for any unauthorized access to or disclosure of your transmissions or data; (iv) for statements or conduct of any third party on or via the Service; (v) for any disputes between users of the Service or between a user of the Service and a Third Party; or (vi) for any other matter relating to the Service or any Third Party. This is a comprehensive limitation of liability that applies to all damages of any kind, including any direct, indirect, special, incidental or consequential damages, whether based on breach of contract, breach of warranty, tort (including negligence), product liability or otherwise, even if an individual advises the Company Parties of the possibility of such damages. The limitations of liability set forth herein are fundamental elements of the basis of the bargain between Company and you. The products, information and services offered on and through the Service would not be provided to you without such limitations.</p>
            <p>Notwithstanding the foregoing, the sole and entire maximum liability of the Company Parties for any reason, and your sole and exclusive remedy for any cause or claim whatsoever, shall be limited to the charges paid by you directly to company via the service, if any, for services provided solely and directly by Company to you in the three (3) months prior to such cause or claim or alternatively if there were no charges paid to the Company a maximum of One Hundred Dollars ($100).</p>
            <p>You agree that regardless of any statute or law to the contrary, any claim you may bring must be filed within one (1) year after the cause of action occurred or it will be permanently barred.</p>
            <p>Some jurisdictions do not allow the disclaimer of certain warranties or the limitation or exclusion of liability for certain types of damages. Accordingly, some of the above disclaimers and limitations may not apply to you.</p>
            <p>If you are a California resident, you shall and hereby do waive California Civil Code Section 1542, which says: “A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which, if known by him must have materially affected his settlement with the debtor.”</p>
            <p className='font-bold mt-2 mb-2'>Purchases and Payments</p>
            <p>Purchase of Services. Your contract for the purchase of Services, both Membership Subscriptions and Goods, if any, is completed once you confirm your purchase and performance of this contract begins as soon as the purchase is complete.</p>
            <p>Membership Subscriptions. Pricing and availability of Membership Subscriptions displayed through the Site are subject to change at any time before you click the button indicating that you want to purchase a Membership Subscription. Company may offer free trials or discounted pricing from time to time. You understand that at the end of a free trial or discount period, unless you cancel prior to the end of such, you will then be charged the Subscription Price as disclosed to you when you signed up for the free trial or discount period.</p>
            <p>Goods. Pricing and availability of Goods displayed through the Site are subject to change at any time before you click the button indicating that you want to purchase a Good. In addition Company may change Subscription pricing at any time, such change to be effective at your next renewal period following the pricing change.</p>
            <p>Payment Processing Methods. Company will make available various payment processing methods to facilitate the purchase of the Service. All payments are made directly with the payment processor; Company does not collect any payments itself. You must abide by any relevant terms and conditions or other legal agreements with third party payment processors, that govern your use of a given payment processing method. Company may add or remove payment processing methods at its sole discretion and without notice to you. Once your purchase is complete the payment processor will charge your credit card or other payment method that you provide to them for any Services purchased, along with any additional applicable amounts (including any taxes). You are solely responsible for all amounts payable associated with purchases you make via the Service.</p>
            <p className='font-bold mt-2 mb-2'>Term, Cancellation and Refunds/Exchanges.</p>
            <p>Subject to this section, the Terms herein will remain in full force and effect while you have a Membership Subscription.</p>
            <p>(i) we may suspend or cancel your rights to use the Service at any time for any reason, or no reason, at our sole discretion, including for any use of the Service in violation of these Terms.</p>
            <p>(ii) you may cancel your use of the Company Service at any time, including any Membership Subscription.</p>
            <p>Upon cancellation of your Membership Subscription under these Terms, whether by you or Us, your Membership Subscription will terminate effective at the end of your then current Membership Subscription period.</p>
            <p>The Company will not have any liability whatsoever to you for any termination of your rights under these Terms, including for termination of your account or deletion of your User Content.</p>
            <p>Returns/Exchanges for Goods purchased through the Service are permitted only under the following circumstances:</p>
            <p>(i) Goods must be returned unused, in the original packaging. Used clothes sold by us are washed and rinsed before sending.</p>
            <p>(ii) You must obtain a Return Merchandize Authorization (RMA) number from us prior to returning or exchanging any item. To receive an RMA from us, email your return/exchange request to models@themccandlessgroup.com.</p>
            <p>(iii) All return/exchange requests must be made no later than fifteen (15) days from your receipt of Goods and we must receive your item no later than thirty (30) days from your receipt of Goods.</p>
            <p>(iv) Users are responsible for payment of postage for returns/exchanges.</p>
            <p className='mt-2 mb-2 font-bold'>Digital Millennium Copyright Act ('DMCA') NOTICE</p>
            <p>We respect the intellectual property rights of others. Per the DMCA, the Company will respond expeditiously to claims of copyright infringement on the Site if submitted to our Copyright Agent as described below. Upon receipt of a notice alleging copyright infringement, Company will take whatever action it deems appropriate within its sole discretion, including removal of the allegedly infringing materials and termination of access for repeat infringers of copyright protected content.</p>
            <p>Procedure for Notifying the Company of Copyright Infringement. If you believe that your intellectual property rights have been violated by us or by a third party who has uploaded materials to our website, please provide the following information to the designated Copyright Agent listed below:</p>
            <p>(i) a description of the copyrighted work or other intellectual property that you claim has been infringed;</p>
            <p>(ii) a description of where the material that you claim is infringing is located on the Site;</p>
            <p>(iii) an address, telephone number, and email address where we can contact you and, if different, an email address where the alleged infringing party, if not us can contact you;</p>
            <p>(iv) a statement that you have a good-faith belief that the use is not authorized by the copyright owner or other intellectual property rights owner, by its agent, or by law;</p>
            <p>(v) a statement by you under penalty of perjury that the information in your notice is accurate and that you are the copyright or intellectual property owner or are authorized to act on the owner's behalf;</p>
            <p>(vi) your electronic or physical signature.</p>
            <p>Company may request additional information before removing any allegedly infringing material. In the event Company removes the allegedly infringing materials, we will immediately notify the person responsible for posting such materials that Company removed or disabled access to the materials. Company may also provide the responsible person with your email address so that the person may respond to your allegations.</p>
            <p>Pursuant to 17 U.S.C. 512(c) Company’s designated Copyright Agent is:</p>
            <p>McCandless Group, LLC</p>
            <p>919-791-6441</p>
            <p>models@themccandlessgroup.com</p>
            <p className='mt-2 mb-2'><strong>Applicable Law and Jurisdiction.</strong> Your use of the Service is governed by and will be enforced under the laws of Californiawithout regard to its conflict of law provisions. You agree to submit to the personal and exclusive jurisdiction of the courts located within the above stated jurisdiction. Any controversy, claim, suit, injury or damage shall be heard on an individual basis and shall not be consolidated with any controversy, claim, suit, injury or damage of any other party. IN ANY CLAIM, ACTION OR PROCEEDING TO ENFORCE ANY RIGHT OR OBLIGATION OF THE PARTIES UNDER THE TERMS OF SERVICE INCLUDING, WITHOUT LIMITATION, RELATING TO YOUR USE OF THE SERVICE, YOU HEREBY WAIVE ANY RIGHT YOU MAY NOW HAVE OR HEREAFTER POSSESS TO A TRIAL BY JURY.</p>
            <p>Any controversy or claim related to the Service or this Terms of Service shall be first be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association then in effect and before a single arbitrator located in the aforementioned jurisdiction. You agree that printed copies of any and all agreements and/or notices in electronic form are admissible in any legal or regulatory proceedings. Company may seek any interim or preliminary relief from a court of competent jurisdiction in the State listed above necessary to protect its rights pending the completion of arbitration. Each party shall assume its own costs of arbitration.</p>
            <p className='mt-2 mb-2'><strong>Miscellaneous.</strong> This Terms of Service constitute the entire agreement between Company and each user of the Service with respect to the subject matter of these Terms of Service.</p>
            <p>a. If any provision of these Terms of Service shall be deemed unlawful, void or for any reason unenforceable by a court of competent jurisdiction, the validity and enforceability of any remaining provisions will not be affected.</p>
            <p>b. The failure of the Company Parties to insist upon strict adherence to any term of these Terms of Service shall not constitute a waiver of such term and shall not be considered a waiver or limit that party’s right thereafter to insist upon strict adherence to that term or any other term contained in these Terms of Service. You may not assign your obligations or rights hereunder to another entity or individual. We may transfer, assign or delegate these Terms of Service and its rights and obligations without your consent.</p>
            <p>c. We shall have no liability to you hereunder if we are prevented from or delayed in performing our obligations, or from carrying on our business, by acts, events, omissions or accidents beyond our reasonable control, including, without limitation, strikes, lock-outs or other industrial disputes (whether involving the workforce of us or any other party), failure of a utility service or transport or telecommunications network, act of God, war, riot, civil commotion, malicious damage, compliance with any law or governmental order, rule, regulation or direction, accident, breakdown of plant or machinery, fire, flood or storm.</p>
            <p>d. No agency, partnership, joint venture, or employment is created as a result of these Terms of Service and you do not have any authority of any kind to bind us in any respect whatsoever.</p>
            <p>e. No action arising out of these Terms of Service or your use of the Service, regardless of form or the basis of the claim, may be brought by you more than one (1) year after the cause of action has arisen (or if multiple causes, from the date the first such cause arose).</p>
            <p>Customer Service. If you have any comments or questions regarding these Terms of Service or wish to report any violation of these Terms of Service, you may contact us at the address below.</p>
            <p>models@themccandlessgroup.com</p>
            <h2 className='text-center font-bold mt-2 text-[22px] mb-2'>Complaints</h2>
            <p>If you would like to file a complaint, please contact our company complaints department via email at support@themccandlessgroup.com. All complaints will be reviewed and addressed within 7 business days via an email reply to your complaint.</p>
            <h2 className='text-center font-bold mt-2 text-[22px] mb-2'>Appeals</h2>
            <p>If you have been depicted in any content and would like to appeal removal of such content, please notify us by sending an email here support@themccandlessgroup.com.</p>
        </div>
    )
}