export default function PrivacyPolicy() {
    return (
        <div className='xl:px-72 md:px-26 px-10 py-8 bg-[#1a0033] text-white'>
            <h1 className='text-center text-[22px] font-bold mb-2'>Privacy Policy</h1>
            <p className='font-bold mt-2 mb-2'>PLEASE READ THIS PRIVACY POLICY CAREFULLY. BY ACCESSING OR USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY ALL THE TERMS OF THIS PRIVACY POLICY AND OUR TERMS OF SERVICE. IF YOU DO NOT AGREE TO SUCH TERMS, EXIT THIS PAGE AND DO NOT ACCESS OR USE THE SERVICE.</p>
            <p className='mt-2 mb-2'>We are committed to respect and protect the privacy of the personal information we obtain from you through the Service and we have created this Privacy Policy to inform you about how we collect, use and share your personal information, and about our privacy practices in general.</p>
            <p className='mt-2 mb-2'>We are always ready to address your questions and concerns regarding this policy and our privacy practices. If you would like to contact customer service, please contact us at the email address at the end of this Privacy Policy.</p>
            <p className='mt-2 mb-2'>We continually strive to find new ways to enhance your experience with the Service and we may modify this Privacy Policy from time to time to reflect changes in our privacy practices. You are encouraged to review this Privacy Policy periodically and to check the “Last Updated” date at the top of the Privacy Policy for the most recent version.  If we make changes to this Privacy Policy, we will notify you here, by email, or by means of notice through the Website, the Application, or any other part of the Service.</p>
            <p className='mt-2 mb-2'><strong>1.  Terms of Service.</strong> Use of the Service is subject to the terms of our <a href='/terms-of-service' target='_self'>Terms of Service</a> through our online form, which is hereby incorporated and made a part of this Privacy Policy. By using the Service, you agree to be bound by our Terms of Service.</p>
            <p className='mt-2 mb-2'><strong>2.  Application of this Privacy Policy.</strong></p>
            <p>2.1.  This policy applies where a) we are acting as a data controller with respect to your personal data, in other words, where we determine the purposes and means of the processing of that personal data, and/or b) where we are acting as a data processor with respect to your personal data, in other words, where we process personal data as instructed by another party.</p>
            <p>2.2.  This policy applies where we are collecting Personally Identifiable Information (as further described below) from individuals and sole proprietors and does not apply to the collection of data from corporate entities.</p>
            <p>2.3. This policy is in accordance with various privacy policy laws and regulations including those applicable in the United States including the California Online Privacy Protection Act (“COPPA”) and the EEU’s General Data Protection Regulation 2016/679 (“GDPR”).</p>
            <p className='mt-2 mb-2'><strong>3.  How we use your data.</strong></p>
            <p>3.1. In this Section 3 we have set out:</p>
            <p>(i)  the general categories of personal data that we may process;</p>
            <p>(ii)  the purposes for which we may process personal data; and</p>
            <p>(iii)  the legal bases of the processing.</p>
            <p>3.2.  Types and Uses of Collected Information. Company collects two types of information about you, “Personally Identifiable Information” and “Non-Personally Identifiable Information.”</p>
            <p>3.3.  Personally Identifiable Information.  Personally identifiable information is information that identifies a specific person.</p>
            <p>3.4.  How we collect Personally Identifiable Information.</p>
            <p>(i)  when you engage in certain activities via the Service, including but not limited to creating an account, sending feedback, or otherwise participating in the Service (collectively, “Identification Activities”) we may ask you to provide certain information about yourself such as your name, address, email address, telephone number and/or any other information you provide to us, to create your account or profile, to send you communications and to provide our Service to you.</p>
            <p>(ii)  if you enroll in the Service through a third party, such as Facebook or Google, or another party, then we may receive Personally Identifiable Information from such third party and by using the Service, you consent to our receipt and sharing of Personally Identifiable Information and its use pursuant to this Privacy Policy by Company. For example, some social networking services allow you to push content from our Service to your contacts or to pull information about your contacts so you can connect with them on or through our Service. Some social networking services also will facilitate your registration for our Service or enhance or personalize your experience on our Service. Your decision to use a social networking service in connection with our Service is voluntary. We reserve the right to use, transfer, assign, sell, share, and provide access to all Personally Identifiable Information and other information about you and your computer, mobile or other device that we receive through third-party social networking services in the same ways described in this Policy as all of your other information.</p>
            <p>3.5.  What kind of Personally Identifiable Information do we collect and how we use it.</p>
            <p>(i)  we may use or share Personally Identifiable Information to provide products and/or service to you, to enable third-parties to provide products and/or services to you, to enter a sweepstakes or contest, to enhance the operation of the Service, improve our marketing and promotional efforts, analyze use of the Service, and tailor your experience with third parties as provided below in this Privacy Policy. We may also use Personally Identifiable Information to troubleshoot, resolve disputes, accomplish administrative tasks, contact you, enforce our agreements with you, including our Terms and Conditions and this Privacy Policy, and to comply with applicable law and cooperate with law enforcement activities.</p>
            <p>(ii)  we may process data about your use of our website and services ('usage data'). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your website and services usage. The source of the usage data is our analytics tracking system. This usage data may be processed for the purposes of analyzing the use of the website and Service. The legal basis for this processing is your consent or our legitimate interests, namely monitoring and improving our website and service.</p>
            <p>(iii)  we may process your account data ('account data').  The account data may include your password and/or User ID, name, telephone number, street address, email address, and other Personally Identifiable Information. The source of the account data is you. The account data may be processed for the purposes of operating our website, providing our Service, ensuring the security of our website and services, maintaining back-ups of our databases and communicating with you. The legal basis for this processing is your consent or our legitimate interests, namely monitoring and improving our website and services.</p>
            <p>(iv)  we may process your information included in your personal profile on our website ('profile data').  The profile data may include your name, address, telephone number, email address, and profile pictures.  The profile data may be processed for the purposes of enabling and monitoring your use of our website and services. The legal basis for this processing is your consent or our legitimate interests, namely monitoring and improving our website and services.</p>
            <p>(v)  we may process information contained in or relating to any communication that you send to us ('correspondence data'). The correspondence data may include the communication content and metadata associated with the communication.  Our website will generate the metadata associated with communications made using the website contact forms. The correspondence data may be processed for the purposes of communicating with you and record-keeping. The legal basis for this processing is your consent or our legitimate interests, namely monitoring and improving our website and services.</p>
            <p>(vi)  we may process information contained in any inquiry you submit to us regarding goods and/or services ('inquiry data'). The inquiry data may be processed for the purposes of offering, marketing and selling relevant goods and/or services to you.</p>
            <p>(vii)  we may process information that you provide to us for the purpose of subscribing to our email notifications and/or newsletters ('notification data'). When you sign up for an account or use certain features, you are opting to receive messages and/or phone calls from other users of the Service and Company.  You cannot opt-out of Administrative Emails. “Administrative Emails” relate to your activity on the Company Service and include but are not limited to emails regarding your account, requests or inquiries, and purchases of products and services, if applicable.  If you do not want to receive promotional emails from us, you may elect to opt-out of receiving promotional emails at any time after registering by e-mailing us at the email listed at the end of this Privacy Policy or by hitting the “unsubscribe” button at the bottom of any of our e-mails.</p>
            <p>(viii)  if you exchange messages with others through the Service, we may store them to process and deliver them, allow you to manage them, and we may review and disclose them in connection with investigations related to the operation and use of the Service. We may choose to not deliver messages that we believe are objectionable, such as spam messages or requests to exchange reviews for compensation.  If you send or receive messages through the Service via SMS text message, we may log phone numbers, phone carriers, and the date and time that the messages were processed. Carriers may charge recipients for texts that they receive. We may also store information that you provide through communications to us, including from phone calls, letters, emails and other electronic messages, or in person. If you are a representative of a business listed on the Service, we may contact you, including by phone or email, using the contact information you provide us, make publicly available, or that we have on record for your business.</p>
            <p>(ix)  we may process any of your personal data identified in this policy where necessary for the establishment, exercise or defense of legal claims, whether in court proceedings or in an administrative or out-of-court procedure. The legal basis for this processing is our legitimate interests, namely the protection and assertion of our legal rights, your legal rights and the legal rights of others.</p>
            <p>(x)  in addition to the specific purposes for which we may process your personal data set out in this Section 3, we may also process any of your personal data where such processing is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</p>
            <p>(xi)  please do not supply any other person's personal data to us unless we prompt you to do so and you have that person’s authorization to provide such, which we may verify via a method chosen in our sole discretion.</p>
            <p>3.6. Non-Personally Identifiable Information. Non-Personally Identifiable Information is information that does not identify a specific person. This type of information may include things like the Uniform Resource Locator (“URL”) of the website you visited before coming to the Site or otherwise participating in the Service, the URL of the website you visit after leaving the Site, the type of browser you are using, your Internet Protocol (“IP”) address, mobile carrier information, mobile device information, or general and/or aggregated location data that does constitute Personally Identifiable Information. We, and/or our authorized third parties may automatically collect this information when you visit or use the Service using electronic tools like Cookies and Web beacons or Pixel tags, as described below in this Privacy Policy.  We use Non-Personally Identifiable Information to troubleshoot, administer the Services, analyse trends, gather demographic information, comply with applicable law, and cooperate with law enforcement activities. We reserve the right to use, transfer, sell, and share aggregated, anonymous data about our users as a group for any lawful business purpose, such as analyzing usage trends and seeking compatible advertisers, sponsors, clients and customers.</p>
            <p className='mt-2 mb-2 font-bold '>4.  Providing your personal data to others.</p>
            <p>4.1.  We may disclose your personal data to one or more of those selected Third-Party Providers of products on or linked from our website, identified on our website for the purpose of enabling them to provide you with products or services.</p>
            <p>4.2.   We do not collect credit card numbers or related data.  Such data is collected and processed by one or more credit card processing third parties.  You should read the privacy policies of these third parties for more information about how they  treat your information.</p>
            <p>4.3.  In addition, as our business changes, we may buy or sell various assets. In the event all or a portion of the assets owned or controlled by us, our parent or any subsidiary or affiliated entity are sold, assigned, transferred or acquired by another company, the information from and/or about our Service users may be among the transferred assets; in other words, unless otherwise stated herein, we have the right to sell user personally identifiable information.</p>
            <p>4.4.  In addition to the specific disclosures of personal data set out in this Section 4, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such disclosure is necessary for the establishment, exercise or defense of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.</p>
            <p className='mt-2 mb-2 font-bold'>5.  Release of Non-Personally Identifiable Information.</p>
            <p>5.1.  We may disclose or share Non-Personally Identifiable Information with Third Party Service Providers and the public. For example, we may share aggregated demographic information (which does not include any Personally Identifiable Information) or use Third Party Service Providers to track and analyze Non-Personally Identifiable usage and volume statistical information from our users to administer the Service. We may also publish this aggregated information for promotional purposes. Such data is collected on our behalf and is owned and used by us.</p>
            <p>5.2.  We may use Third Party Service Providers to serve ads when you participate in the Service. These companies may use Non-Personally Identifiable Information about your visits and use of the Service, and visits to other websites or locations to provide, through the use of network tags, advertisements about goods and services that may be of interest to you.  Our advertising service vendors and other Third Parties will at times also use tracking technologies to serve you advertisements tailored to interests you have shown by browsing on this Service and other sites, applications, destinations, and services you have visited, and to determine whether you have seen a particular advertisement before to avoid sending you duplicate advertisements, and for other lawful business purposes. In doing so, these Third Parties may collect non-personally identifiable data including for example the make, model, settings, specifications (e.g., CPU speed, connection speed, browser type, operating system, device identifier) and geographic location of your computer, mobile or other device, as well as date/time stamp, IP address, pages visited, time of visits, content viewed, ads viewed, the site(s), application(s), destination(s), and/or service(s) you arrived from, and other clickstream data. The use of tracking technologies by Third Parties is subject to their own privacy policies, not this Privacy Policy, and we have no responsibility or liability in connection therewith. If you do not want the services that tracking technologies provide, you may be able to opt-out by visiting http://www.aboutads.info.</p>
            <p className='mt-2'><strong>6.  Choices on Collection/Use of Information.</strong>  You can always choose not to provide certain information, although a certain level of information is required to engage and participate in the Service.</p>
            <p className='mt-2 font-bold mb-2'><strong>7.  About cookies.</strong></p>
            <p>7.1.  A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.</p>
            <p>7.2.  Cookies may be either 'persistent' cookies or 'session' cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.</p>
            <p>7.3.  Cookies do not typically contain any information that personally identifies a user, but personal information that we store about you may be linked to the information stored in and obtained from cookies.</p>
            <p>7.4.  We use cookies for the following purposes:</p>
            <p>(i)  authentication - we use cookies to identify you when you visit our website and as you navigate our website.</p>
            <p>(ii)  status - we use cookies to help us to determine if you are logged into our website.</p>
            <p>(iii)  security - we use cookies as an element of the security measures to protect our website and services generally.</p>
            <p>(iv)  advertising - we use cookies to help us to display advertisements that may be relevant to you.</p>
            <p>(vii)  analysis - we use cookies to help us to analyze the use and performance of our website and services; and</p>
            <p>(viii)  cookie consent - we use cookies to store your preferences in relation to the use of cookies more generally.</p>
            <p className='mt-2 mb-2'><strong>8. Cookies used by our service providers and/or affiliates.</strong></p>
            <p>8.1.  Our service providers, affiliates and partners use cookies and those cookies may be stored on your computer when you visit our website.</p>
            <p>8.2.  We may use Google Analytics or similar tools to analyze the use of our website. Google Analytics gathers information about website use by means of cookies. The information gathered relating to our website is used to create reports about the use of our website. Google's privacy policy is available at: https://www.google.com/policies/privacy/.</p>
            <p className='mt-2 mb-2'><strong>9.  Managing cookies</strong></p>
            <p>9.1.  Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:</p>
            <p>(i)  https://support.google.com/chrome/answer/95647?hl=en (Chrome);</p>
            <p>(ii)https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences (Firefox);</p>
            <p>(iii)  http://www.opera.com/help/tutorials/security/cookies/ (Opera);</p>
            <p>(iv)https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies (Internet Explorer);</p>
            <p>(v)  https://support.apple.com/kb/PH21411 (Safari); and</p>
            <p>(vi)https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy (Edge).</p>
            <p>9.2.  Blocking all cookies will have a negative impact upon the usability of many websites.</p>
            <p>9.3.  If you block cookies, you will not be able to use all the features on our website.</p>
            <p className='mt-2 mb-2'><strong>10.  Local Device Storage and other Tracking Technologies; Do Not Track (DNT):</strong></p>
            <p>10.1.  The Service will at times place and/or store code or other types of information and/or devices (e.g., “cookies”) on your computer, mobile or other device (“Local Device Storage”). We may use Local Device Storage for any lawful business purpose, including without limitation to determine which of our messages have been opened by recipients so we can gauge the effectiveness of marketing campaigns, to control the display of ads, to track usage patterns, the movements of individual users, and your geographic location, to help diagnose problems with our servers, to gather broad demographic information, to analyze trends, to conduct research, to deliver editorial content, to record registration and personalization information, and to otherwise administer the Service. For example, if you register on any part of the Service and are given the option to save your user name and password, we may provide this convenience to you via Local Device Storage. Local Device Storage may also collect and store your personally identifiable information, which may be shared with our parent, subsidiaries, and affiliates and other companies.</p>
            <p>10.2.  If you do not want Local Device Storage, your computer, mobile or other device may include an option that allows you to not accept it. However, if you disable Local Device Storage, some portions of the Service may not function properly.</p>
            <p className='mt-2 mb-2'><strong>11.  Analytics.</strong></p>
            <p>11.1. We continuously improve our websites and our products, and we utilize different third-party web analytics tools to help us do so. We are interested in how visitors use our websites, our desktop tools, mobile applications, or our API, what they like and dislike, and where they have problems. Our products, desktop tools, mobile applications and API use analytical tools to understand feature usage patterns, to enhance and improve your product experience and offer you specific usage tips and guidance. In connection with normal business operations, as well as to increase functionality and enhance your user experience, this usage information may be linked to personal information that we have about individual users. We maintain ownership of this data and we do not share this type of data about individual users with third parties.  11.2. This information is used solely to assist us in maintaining a more effective and useful websites and products for our customers. This data will not be shared with third parties without your prior consent or unless required by law.</p>
            <p className='mt-2 mb-2'><strong>12.  Transfer of Information.</strong></p>
            <p>12.1  Your information may be transferred to, and maintained on, servers and databases located outside of your state, province, country or other governmental jurisdiction where the privacy laws may not be as protective as your jurisdiction. Please be advised that we may transfer your information to and from any state, province, country or other governmental jurisdiction, and process it in the United States or elsewhere. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to any such transfer.</p>
            <p className='mt-2 mb-2'><strong>13.  Security of Information.</strong></p>
            <p>13.1. In the event you are provided with an opportunity to establish and account or profile on our Site, you may be able to access your Personally Identifiable Information via the Service with your password and username. This password is encrypted. We advise against sharing your password with anyone.  If you access your account via a third-party site or service, you may have additional or different sign-in protections via that third-party site or service. You need to prevent unauthorized access to your account and Personal Information by selecting and protecting your password and/or other sign-in mechanism appropriately and limiting access to your computer, browser, or mobile device by signing off after you have finished accessing your account. Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time. If we believe that the security of your information may have been compromised, we may seek to notify you of that development.</p>
            <p>13.2. We are committed to taking all reasonable precautions to safeguard the privacy of personal information which has been provided by its users. We use technical, contractual, administrative and physical security steps to protect your personal information. Security measures such as restricted access and the use of passwords and encryption have been adopted to protect your personal information against loss or theft, as well as unauthorized access, disclosure, copying, use or modification. Our employees have been trained to respect your privacy at all times and those employees with access to your personal information shall use your personal information strictly in accordance with this Privacy Policy. We will protect your credit card information by using industry standard encryption technology.</p>
            <p>13.3. Please be aware that no data transmission over the Internet or via e-mail is completely secure and therefore we cannot guarantee protection of all personal information in all cases. For example, we cannot guarantee protection against interception, misappropriation, misuse, or alteration, or that your information will not be disclosed or accessed by the unauthorized acts of others. Consequently, we cannot ensure or warrant the security of any information you transmit to us, and you do so at your own risk. If you provide us with your credit card number, you should not send it electronically unless the email is encrypted, or your browser indicates that the access to our website is secure. Materials posted to online forums such as bulletin boards or chat rooms are public, not secure, and may be viewed by anyone. Any personal information you post may be collected and used by anyone and may result in unsolicited messages from other parties.</p>
            <p className='mt-2'><strong>14. Notice of Privacy Rights to California Residents.</strong> California law requires that we provide you with a summary of your privacy rights under the California Online Privacy Protection Act (“COPPA”) and the California Business and Professions Code. As required by COPPA, we will provide you with the categories of Personally Identifiable Information that we collect through the Service and the categories of third-party persons or entities with whom such Personally Identifiable Information may be shared for direct marketing purposes at your request. California law requires us to inform you, at your request, (1) the categories of Personally Identifiable Information we collect and what third parties we share that information with; (2) the names and addresses of those third parties; and (3) examples of the products marketed by those companies. COPPA further requires us to allow you to control who you do not want us to share that information with. To obtain this information, please send a request by email or physical mail to the address found below. When contacting us, please indicate your name, address, email address, and what Personally Identifiable Information you do not want us to share with our marketing partners. The request should be sent to the attention of our legal department and labeled “California Customer Choice Notice.” Please allow 30 days for a response. Also, please note that there is no charge for controlling the sharing of your Personally Identifiable Information or requesting this notice.</p>
            <p className='mt-2'><strong>15.  Age.</strong>  The Service is not directed to children under the age of eighteen (18). If you become aware that your child has provided us with personal information please contact us at the email address listed below. If we become aware that a child under this age has provided us with personal information, we will take steps to remove such information and terminate the child’s account.</p>
            <p className='mt-2 mb-2'><strong>16.  Additional terms that apply to some residents of the European Economic Area (EEA).</strong></p>
            <p>In addition to the rights already recorded above, if you are based in the EEA, you may have the following additional rights in relation to the personal information we hold about you, in accordance with The General Data Protection Regulation 2016/67.</p>
            <p className='mt-2 mb-2'><strong>17.  Additional Rights.</strong></p>
            <p>17.1. In this Section 17, we have summarized the rights that you may have under data protection laws in the EEA. Some of the rights are complex, and not all of the details have been included in our summaries. Accordingly, you should read the relevant laws and guidance from the regulatory authorities for a full explanation of these rights.</p>
            <p>17.2. Your principal rights under data protection laws in the EEA are:</p>
            <p>(i)  the right to access;</p>
            <p>(ii)  the right to rectification;</p>
            <p>(iii)  the right to erasure;</p>
            <p>(iv)  the right to restrict processing;</p>
            <p>(v)  the right to object to processing;</p>
            <p>(vi)  the right to data portability;</p>
            <p>(vii)  the right to complain to a supervisory authority; and</p>
            <p>(viii)  the right to withdraw consent.</p>
            <p>17.3. You have the right to confirmation as to whether we process your personal data and, where we do, access to the personal data, together with certain additional information. That additional information includes details of the purposes of the processing, the categories of personal data concerned and the recipients of the personal data. Providing the rights and freedoms of others are not affected, we will supply to you a copy of your personal data. The first copy will be provided free of charge, but additional copies may be subject to a reasonable fee.</p>
            <p>17.4. You have the right to have any inaccurate personal data about you rectified and, considering the purposes of the processing, to have any incomplete personal data about you completed.</p>
            <p>17.5. In some circumstances you have the right to the erasure of your personal data without undue delay. Those circumstances include: the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed; you withdraw consent to consent-based processing; you object to the processing under certain rules of applicable data protection law; the processing is for direct marketing purposes; and the personal data have been unlawfully process. However, there are exclusions of the right to erasure. The general exclusions include where processing is necessary: for exercising the right of freedom of expression and information; for compliance with a legal obligation; or for the establishment, exercise or defense of legal claims.</p>
            <p>17.6. In some circumstances you have the right to restrict the processing of your personal data. Those circumstances are: you contest the accuracy of the personal data; processing is unlawful but you oppose erasure; we no longer need the personal data for the purposes of our processing, but you require personal data for the establishment, exercise or defense of legal claims; and you have objected to processing, pending the verification of that objection. Where processing has been restricted on this basis, we may continue to store your personal data. However, we will only otherwise process it: with your consent; for the establishment, exercise or defense of legal claims; for the protection of the rights of another natural or legal person; or for reasons of important public interest.</p>
            <p>17.7. You have the right to object to our processing of your personal data on grounds relating to your particular situation, but only to the extent that the legal basis for the processing is that the processing is necessary for: the performance of a task carried out in the public interest or in the exercise of any official authority vested in us; or the purposes of the legitimate interests pursued by us or by a third party. If you make such an objection, we will cease to process the personal information unless we can demonstrate compelling legitimate grounds for the processing which override your interests, rights and freedoms, or the processing is for the establishment, exercise or defense of legal claims.</p>
            <p>17.8. You have the right to object to our processing of your personal data for direct marketing purposes (including profiling for direct marketing purposes). If you make such an objection, we will cease to process your personal data for this purpose.</p>
            <p>17.9. You have the right to object to our processing of your personal data for scientific or historical research purposes or statistical purposes on grounds relating to your particular situation, unless the processing is necessary for the performance of a task carried out for reasons of public interest.</p>
            <p>17.10.  To the extent that the legal basis for our processing of your personal data is:</p>
            <p>(i)  consent; or</p>
            <p>(ii)  that the processing is necessary for the performance of a contract to which you are party or in order to take steps at your request prior to entering into a contract, and such processing is carried out by automated means, you have the right to receive your personal data from us in a structured, commonly used and machine-readable format. However, this right does not apply where it would adversely affect the rights and freedoms of others.</p>
            <p>17.11.  To the extent that the legal basis for our processing of your personal information is consent, you have the right to withdraw that consent at any time. Withdrawal will not affect the lawfulness of processing before the withdrawal.</p>
            <p>17.12. If you consider that our processing of your personal information infringes data protection laws, you have a legal right to lodge a complaint with a supervisory authority responsible for data protection.</p>
            <p>17.13.  You may access your personal information that we hold by contacting us using the contact details below.  We will provide you with a copy of the personal information we keep about you.  However, we reserve the right to charge you a reasonable amount for providing copies of any personal information you request, to take into account the time, cost and effort involved.</p>
            <p>17.14.  You may request that the personal information we hold about you be corrected by contacting us.  If we do not agree to your request for a correction, you may then request that we take reasonable steps to attach to the information a statement of the correction sought but not made.</p>
            <p>17.15.  Please be aware that some of these rights may be limited or unavailable where we have an overriding interest or legal obligation to continue to process the data, or where data may be exempt from disclosure. 18.  Customer Service. If you have any comments or questions regarding Privacy Policy or wish to report any violation of this Privacy Policy, you may contact us at the address below.</p>

        </div>
    )
}