
const ADD_ACCOUNT = 'ADD_ACCOUNT'
const CHECK_USER_ACCOUNT = 'CHECK_USER_ACCOUNT'
const UPDATE_USER_DETAILS_IN_WEBSITE_ERROR = 'UPDATE_USER_DETAILS_IN_WEBSITE_ERROR'

const REQ_FROM_REGISTER = 'register'
const REQ_FROM_LOGIN = 'login'
const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'
const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'
const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
const MERGE_ACCOUNT = 'MERGE_ACCOUNT'
const LOGIN_MERGE = 'LOGIN_MERGE'
const MERGE_ACCOUNT_FROM_RESET_PASSWORD = 'MERGE_ACCOUNT_FROM_RESET_PASSWORD'
const REGISTER = 'REGISTER'

const restrictedDomains = ['julianabondeofficial.com', 'jessicediel.us', 'dejanadaily.com', 'dixklebert.com', 'melicediel.us', 'biahmadu.com']

module.exports = {
    ADD_ACCOUNT,
    CHECK_USER_ACCOUNT,
    UPDATE_USER_DETAILS_IN_WEBSITE_ERROR,
    REQ_FROM_REGISTER,
    REQ_FROM_LOGIN,
    UPDATE_PASSWORD_ERROR,
    RESET_PASSWORD_ERROR,
    UPDATE_PASSWORD,
    MERGE_ACCOUNT,
    LOGIN_MERGE,
    MERGE_ACCOUNT_FROM_RESET_PASSWORD,
    REGISTER,
    restrictedDomains
}
